from random import *
id = range(1, 21)
id = list(id)
shuffle(id)
winners = sample(id, 4)
print("당첨자 발표")
print("치킨 당첨자 : {}".format(winners[0]))
print("커피 당첨자 : {}".format(winners[1:]))
print("축하합니다.")
#shuffle(id)
#print("-- 당첨자 발표 --")
#print("치킨 당첨자 : ", sample(id, 1))
#print("커피 당첨자 : ", sample(id, 3))
#print("-- 축하합니다 --")